// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8TilsvYFsYaVoeY3Q42Eq-3fDqB-5wdQ',
    appId: '1:983680606089:web:73b7dd6cca87271a634b58',
    messagingSenderId: '983680606089',
    projectId: 'login-app-da167',
    authDomain: 'login-app-da167.firebaseapp.com',
    storageBucket: 'login-app-da167.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD-4XvF2Sh1iJrYRqnazu0-Pfop92Pz9Y',
    appId: '1:983680606089:android:fa161180b0a14b78634b58',
    messagingSenderId: '983680606089',
    projectId: 'login-app-da167',
    storageBucket: 'login-app-da167.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChCmqvhfGzZsH8eT8qAB8hjoVK4cDHIDw',
    appId: '1:983680606089:ios:635b01306929cd54634b58',
    messagingSenderId: '983680606089',
    projectId: 'login-app-da167',
    storageBucket: 'login-app-da167.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChCmqvhfGzZsH8eT8qAB8hjoVK4cDHIDw',
    appId: '1:983680606089:ios:e5b582ffa7369a08634b58',
    messagingSenderId: '983680606089',
    projectId: 'login-app-da167',
    storageBucket: 'login-app-da167.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
